jx:
  imagePullSecrets: []
  secrets:
    adminUser:
      password: todo
      username: todo
    hmacToken: todo
    pipelineUser:
      email: jenkins-x@googlegroups.com
      token: todo
      username: jenkins-x-labs-bot
jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: eks
    registry: ecr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: -tekton-pipelines.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: vault
  vault: {}
  webhook: lighthouse
jxRequirementsIngressExternalDNS:
  enabled: false
jxRequirementsIngressTLS:
  enabled: false
jxRequirementsVault:
  enabled: true
